const {
    APPLICATION_BASE_URL,
    MONGO_PORT,
    MONGO_APPLICATION_URI,
    MONGO_APPLICATION_DATABASE,
    MONGO_APPLICATION_USERNAME,
    MONGO_APPLICATION_PASSWORD,
    NODE_ENV,
    PORT,
} = process.env;

module.exports = {
    APPLICATION_BASE_URL,
    MONGO_PORT,
    MONGO_APPLICATION_URI,
    MONGO_APPLICATION_DATABASE,
    MONGO_APPLICATION_USERNAME,
    MONGO_APPLICATION_PASSWORD,
    NODE_ENV,
    PORT,
};