const {
    MONGO_APPLICATION_URI,
    MONGO_APPLICATION_DATABASE,
    MONGO_APPLICATION_USERNAME,
    MONGO_APPLICATION_PASSWORD
} = require('dotenv').load().parsed;

module.exports = {
    MONGO_PORT: 27017,
    MONGO_APPLICATION_URI,
    MONGO_APPLICATION_DATABASE,
    MONGO_APPLICATION_USERNAME,
    MONGO_APPLICATION_PASSWORD,
    APPLICATION_HTTP_PORT: 8080,
    APPLICATION_BASE_URL: 'http://localhost'
};